### PR TITLE
Update README examples to use new index DSL

### PR DESCRIPTION
**Pull request by CDThomas**
The PR updates the examples in the README to reflect the changes in https://github.com/cipherstash/activestash/pull/79.

### CODE REVIEW

**Comment by CDThomas** [comment]
Note that I haven't documented the `index_assoc` method because it probably needs a more detailed explanation of when and why to use it (and I'm not fully across this yet). How do you want to approach docs for `index_assoc` @freshtonic? Mind if I add a note to the card and leave that one for you?

**Comment by freshtonic** [comment]
@CDThomas `index_assoc` allows you to search for a parent model using values from an associated record. Honestly, it's a bit half baked at the moment because we can't support anything other than a single associated record (a `belongs_to` or `has_one`).

I'm ok with it being undocumented for now. It will help with Healthbank but i'm ok for it not to be publicly documented.

**Review by freshtonic — APPROVED** [review]
Looks good, @CDThomas. Thank you for tackling this.

**Review by fimac — APPROVED** [review]
🙌🏼  Nice!

**Pull request merged**
